import type { Metadata } from "next";
import { ThemeProvider } from "@/lib/themes";
import "./globals.css";

export const metadata: Metadata = {
	title: "DevRoast",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	);
}
